# Generated by Django 5.0.1 on 2024-01-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
