# Generated by Django 5.0.1 on 2024-01-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_quizsession_timestamp_delete_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='final_score',
            field=models.CharField(max_length=50),
        ),
    ]
