# Generated by Django 5.0.1 on 2024-01-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_quizsession_final_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='final_score',
            field=models.IntegerField(),
        ),
    ]
