# Generated by Django 5.0 on 2024-05-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userresponse'),
        ('home', '0007_alter_quizsession_final_score'),
    ]

    operations = [
    ]
